### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by HenryTabima** [ph1p/vuepress-jsdoc#1]
Hi, i like very much this project and i would like to contribute. Im have couple of years codign but im new in open source world. if you have any sugestion to start, i'll thank you a lot.

**Comment by ph1p** [comment]
Hi! Nice to hear (: The only thing you have to do is forking this repository. Once you've done that, you can work on the code. If you have any meaningful changes (bugfixes, features, updates, etc.), you can easily create a PR using the GitHub interface.

**Comment by HenryTabima** [comment]
thank you. im going to make it work on my pc (for some reason running `npm install` doesnt work), and then read the code and start working in some meaningful changes
