### ISSUE TITLE
Override jsdoc configuration

### ISSUE THREAD

**Issue by deka** [ph1p/vuepress-jsdoc#10]
Hi,
I have an issue when i generate the doc with underscore in source path.
If i undestand jsdoc, the jsdoc options "[excludePattern](http://usejsdoc.org/about-configuring-jsdoc.html)" can solve my issue.

Is there a way to override jsdoc options ? perhaps with [this jsdoc2md option](https://github.com/jsdoc2md/jsdoc-api#optionsconfigure--string) ?

**Comment by ph1p** [comment]
Hi @deka,

Unfortunately there is no way to override these options yet, but I can see if I can add a way to set them.

If you only want to exclude files or folders with an underscore, you can simply write this:

````
vuepress-jsdoc --exclude _*.js,*_folderName*

**Comment by deka** [comment]
Thanks, but i do not need to exclude elements.
I try to build with an underscore. I need excludePattern option to remove underscore.

No way to add a path to jsdoc config file with jsdoc2md options ([options.configure](https://github.com/jsdoc2md/jsdoc-api#optionsconfigure--string)) ?

**Comment by ph1p** [comment]
@deka Could you send me your project or an example?  So I can implement this feature and test it out.
Thanks in advance

**Comment by deka** [comment]
Sorry i can't send you an example.
i build with TFS/VSTS and i can't remove the underscore.

You can reproduce by having part of the path that starts with an underscore, like : 
d:/_test/projet-vue

**Comment by ph1p** [comment]
Ok thanks. I'll check it and send you an update, maybe this is only an issue with windows.

Can you send me the cli command you entered or do you call it from ./project-vue?

**Comment by deka** [comment]
Thanks,
Jsdoc say : 
"Any file starting with an underscore, or in a directory starting with an underscore, will be ignored (source.excludePattern)."
http://usejsdoc.org/about-configuring-jsdoc.html#default-configuration-options

**Comment by ph1p** [comment]
I've added the `-c` and `--jsDocConfigPath` argument. Now you can set an absolut path to your jsdoc.json config. This feature is experimental. Please test it and give me your feedback.

**Comment by deka** [comment]
Thanks, 
It works as expected. :)

**Comment by ph1p** [comment]
Cool (:
