### ISSUE TITLE
Custom title should also be used for the actual headline

### ISSUE THREAD

**Issue by juliusknorr** [ph1p/vuepress-jsdoc#14]
When specifying a custom title with the `@vuepress` annotation, it should also be used in the generated markdown file.

Using:
```
/**
 * @vuepress
 * ---
 * title: Your custom title
 * ---
 */
```

Actual output:
```
---
title: Your custom title
---
# action 
```

Expected output:
```
---
title: Your custom title
---
# Your custom title 
```

**Comment by ph1p** [comment]
Goo idea! I'll implement it tomorrow ;)

**Comment by ph1p** [comment]
Added in `1.5.0`

**Comment by juliusknorr** [comment]
Awesome. Thanks a lot @ph1p for the quick implementation.

**Comment by ph1p** [comment]
Your welcome (:

**Comment by ChasLui** [comment]
I want to control whether to use h1 or a custom title via the Options parameter.

**Comment by ph1p** [comment]
> I want to control whether to use h1 or a custom title via the Options parameter.

I'll add it. Do you have a suggestion as to what I could call the parameter?

**Comment by ph1p** [comment]
@ChasLui now you can use
```
/*
 * @vuepress
 * ---
 * title: Your custom title
 * headline: You custom headline
 * ---
 */
```
The `headline` is your custom h1 tag. `title` is used as fallback and the filename is used as `title` fallback. Hope this is what you wanted.
