### ISSUE TITLE
'exlude by config' on files

### ISSUE THREAD

**Issue by Seanitzel** [ph1p/vuepress-jsdoc#17]
I've been using this great package without any problems for the last few weeks,
but today after adding some docs to some files and trying to generate the new docs with them included i get this strange msg on these files:

![image](https://user-images.githubusercontent.com/16267397/56423726-2a9ccd80-62b6-11e9-92c6-4a024648d0f6.png)

I went through any configuration i have in the whole project to try and find what might cause this to happen without any success.

Other folders which are excluded have this msg:

![image](https://user-images.githubusercontent.com/16267397/56423818-810a0c00-62b6-11e9-9ffa-efcdf93d7275.png)

This is how that folder appears in the generated config:

![image](https://user-images.githubusercontent.com/16267397/56423882-a8f96f80-62b6-11e9-8c4a-4e529ad1fafa.png)

Would appreciate help :)

**Comment by ph1p** [comment]
I'll take a look at it ;) can you please upload a zip or something else, so I can easier reproduce and fix it

**Comment by Seanitzel** [comment]
[bug.zip](https://github.com/ph1p/vuepress-jsdoc/files/3098296/bug.zip)

Found the bug :)
Apparently it 'exludes' files when somewhere inside them some version of returning an array appears...
```
@returns {[]}
```
That includes combinations of that with other parameters or when they contain a type.

to reproduce just run:
```
yarn
yarn docs
```

output: 

![image](https://user-images.githubusercontent.com/16267397/56427242-d00a6e00-62c3-11e9-8825-a63c7c406bd2.png)

**Comment by ph1p** [comment]
Thank you.  Unfortunately this is a jsdoc error :/ I have added more meaningful errors.

You can do this:
```javascript
@returns {Array}
```
