### ISSUE TITLE
Not generating docs for classes with a constructor

### ISSUE THREAD

**Issue by Seanitzel** [ph1p/vuepress-jsdoc#22]
**Desciption of the bug**
Docs are not generated for any class with a constructor in versions 1.8.0 and 1.7.4.

**To Reproduce**
1. Create a new folder and create a 'src' folder within it.
2. Create a js file inside the src folder and write any class with a constructor.
3. open a terminal and navigate to the project folder, run 'vuepress-jsdoc'
4. See that the docs for the file are not generated.

**Expected behavior**
Docs are generated.

**Node**
 - Node-Version: 12.7.0

**Additional context**
Temporary fix - use version 1.7.2 of vuepress-jsdoc.
Finding the bug took a good few hours...

**Comment by ph1p** [comment]
Thanks for reporting! (: I'll take a look at it and publish a fix as soon as possible

**Comment by ph1p** [comment]
Unfortunately, I can't reproduce it or I've been following your instructions incorrectly. (macOS)
What OS do you use?

I've created the following structure:

* my-tool  `<-- run vuepress-jsdoc inside`
  * src
    * **class.js** 
  * documentation
    * code
      * config.js
      * README.md
      * **class.md**

**class.js**
```javascript
class MyClass {
  /**
   * My Constructor
   * @param {string} param
   */
  constructor(param = '') {

  }
}
```

**RESULT:**
**class.md**
```markdown
---
title: class
---

# class

<a name="MyClass"></a>

## MyClass
**Kind**: global class  
<a name="new_MyClass_new"></a>

### new MyClass(param)
My Constructor


| Param | Type |
| --- | --- |
| param | <code>string</code> | 
```

**Comment by Seanitzel** [comment]
I'm using macOS as well.

Sorry i wasn't more spesific!
The issue accures only when exporting the class in the class definition line, 
e.g

```
/**
 * My Class
 */
export class cls {
    constructor(x) {
    }
}
```

also happens when exporting default.

Just found out it does not happen if you export at the bottom of the file.

**Comment by ph1p** [comment]
Thank you! Hopefully I can find the bug tomorrow and fix it.

**Comment by ph1p** [comment]
Okay, I found the bug. In version 1.7.2 jsdoc-to-markdown@4 is installed. I updated this plugin because it fixes errors with node 12 and additionally updates jsdoc-api. This is also where the bug is. In the new version of the jsdoc-api it occurs.

The temporary solution I found is to write the `@class` annotation.

```javascript
/**
 * firstClass (no annotation needed)
 */
class firstClass {
  constructor(x) {}
}

/**
 * secondClass
 * @class secondClass
 */
export class secondClass {
  constructor(x) {}
}
```

**Some links**
https://github.com/jsdoc2md/jsdoc-to-markdown/releases
https://github.com/jsdoc/jsdoc/blob/master/CHANGES.md

https://github.com/jsdoc/jsdoc/issues/1132

**Comment by Seanitzel** [comment]
I see...

Oh well, guess we'll use the work around for now.

Thanks for the quick response :)

**Comment by ph1p** [comment]
@Seanitzel You're welcome (:
I'll keep an eye on it!
