### ISSUE TITLE
Security issue with  handlebars 

### ISSUE THREAD

**Issue by deka** [ph1p/vuepress-jsdoc#24]
**Describe the bug**
Security issue with dependency  handlebars.

**To Reproduce**
Yarn audit

**Expected behavior**
No high level issue

**Additional context**

│ high          │ Prototype Pollution
│ Package       │ handlebars                                                   │
│ Patched in    │ >=4.5.3                                                      │
│ Dependency of │ vuepress-jsdoc                                               │
│ Path          │ vuepress-jsdoc > jsdoc-to-markdown > dmd > handlebars        │
│ More info     │ https://www.npmjs.com/advisories/1325

**Comment by ph1p** [comment]
Thanks for reporting! I‘ll take a look at it;)
