### ISSUE TITLE
Throw error if doc fails to parse

### ISSUE THREAD

**Issue by GreenImp** [ph1p/vuepress-jsdoc#31]
**Is your feature request related to a problem? Please describe.**
If a document fails to parse, it still continues to generate all the other files and exits with code `0`:

> ERROR: Unable to parse a tag's type expression for source file  /src/my-file.js in line 88 with tag title ...
> error ./src/my-file.js -> ./documentation/code/my-file.md

Still completes with:

> Finished! 👍
> Process finished with exit code 0

If there are a lot of files, you can miss that some may have failed to parse.
It also means that it can't be used easily in CI tools, as they look for a script to provide an error code on failure, and will incorrectly think that everything was successful.

**Describe the solution you'd like**
I think it could be helpful for the script to throw an error message and error code if a document fails to be written.

I think the error code just needs to be non-zero (Usually seems to be `1`).

I'm not sure whether it would also be good to stop processing on the first failure. The benefit is that it wont spend more time generating documents when it's not necessary; the downside is that there may be other files that don't parse, and it wont catch them in one go.

**Comment by ph1p** [comment]
Hi @GreenImp 

Good point! Maybe I can add a formatted result table at the end. Like jest does:

<img width="259" alt="Screenshot 2020-08-03 at 10 59 31" src="https://user-images.githubusercontent.com/15351728/89165156-6ecde300-d578-11ea-8f9e-d6716f0f62ad.png">

So you can see the errors at the end. Additionally I can add a flag to stop the process completely if an error occurs.

What do you think?

**Comment by GreenImp** [comment]
I like the idea of the result table! That would be really handy, if it's not too difficult to accomplish.

The "stop on error" flag is a good idea. I like it.

I think the most beneficial thing for me is just to be able to get an error code response, like Jest does, if there's an error. So Travis will notify me if it fails.

**Comment by ph1p** [comment]
I've updated the CLI and now you can use the `--ci` flag or set CI=true as environment variable.

This the new result:

<img width="448" alt="Screenshot 2020-08-03 at 21 26 06" src="https://user-images.githubusercontent.com/15351728/89219390-fbf05680-d5cf-11ea-9695-6cbd69319434.png">

I'll release it as fast as I can.

**Comment by ph1p** [comment]
Okay (: The new version is now released (3.1.0). @GreenImp

**Comment by GreenImp** [comment]
That was really quick! Thanks. That results table looks really nice.

Using the `--ci` argument, I can see the errors being thrown but, for some reason, the script still exits with a `0` exit code, which is taken by success.
I don't have any experience with responses from CLI scripts in node, so not sure why throwing the errors wouldn't do the job (Seems like it should to me). But node is saying this:

> (node:5760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
>
> (node:5760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>
> The command "npm run build:docs" exited with 0.

So I'm wondering if the fact it's thrown inside an `async` method is the issue? Maybe it needs to be thrown higher up the chain, outside of the async methods.

**Comment by ph1p** [comment]
I'll take a look at it ;)

**Comment by GreenImp** [comment]
Cheers!

I've just found this: https://stackoverflow.com/a/5266239

Which looks like it will do the job.
It also means that you don't need to throw the error as well, as they already show in the process.

Maybe just calling `process.exit(1)`at the end of the whole script, if there are errors?

**Comment by ph1p** [comment]
Ok, I decided to drop the `--ci` command, maybe we can add it later and hide some larger output for example.
`process.exit()` is now always executed, after all files are processed. If there were errors, it ends with `1` and if not then with `0`.

**Comment by GreenImp** [comment]
That's perfect! Works like a charm :) Thanks so much for getting this sorted and so quickly.

**Comment by ph1p** [comment]
You're welcome (:
