### ISSUE TITLE
Can't exclude specific files in a directory

### ISSUE THREAD

**Issue by GreenImp** [ph1p/vuepress-jsdoc#33]
**Describe the bug**
Using the `exclude` flag doesn't seem to work when trying to exclude a file in a particular directory.
You can exclude any file that matches a particular name, or all files within a directory. But not a particular file inside a particular directory.

**To Reproduce**
Given the following file structure:

```
/foo.js
/directory/foo.js
/directory/bar.js
```

Using the following flag:
```
--exclude ./foo.js
```
Will exclude both `/foo.js` and `/directory/foo,js`.

And this:
```
--exclude ./directory
```
Will exclude `/directory/foo.js`, and `/directory/bar.js`.

But this doesn't exclude anything:
```
--exclude ./directory/foo.js
```

**Expected behavior**
I would expect to be able to exclude individual files inside directories.

E.g.:
```
--exclude ./directory/foo.js
```

Would exclude `/directory/foo.js`. And _not_ exclude `/foo.js` or `/directory/bar.js`.

**Node (please complete the following information):**
 - Node-Version: 14.3.0

**Comment by ph1p** [comment]
Hi (: It should now work with `v3.4.0`. Maybe this will help you to write your pattern: https://github.com/micromatch/micromatch#ismatch. This is the moduel I've used inside `vuepress-jsdoc`.
