### ISSUE TITLE
Embedded Markdown inside .vue files not rendered

### ISSUE THREAD

**Issue by RCK-DEV** [ph1p/vuepress-jsdoc#37]
In one the examples of Vue Styleguidist in combination with Vuepress you can see that the embedded Markdown inside a .vue is rendered. 

Example demo page: https://vue-styleguidist.github.io/docgen/components/Button/Button.html#props
Demo source code: https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/examples/docgen/src/components/Button/Button.vue

Since vuepress-jsdoc is utilizing both Vue Styleguidist and Vuepress i wonder why the embedded Markdown doesn't seem to work with vuepress-jsdoc. Any clue what's causing this?

**Comment by ph1p** [comment]
This should be fixed now. Previously I simply wrote a parser for Markdown based on `vue-docgen-api`, I have now thrown this out and replaced it with `vue-docgen-cli`. Hope this will work for you (: You can try it with the new version (v3.3.0)

**Comment by RCK-DEV** [comment]
Ha! Awesome! Good to see that you've fixed it so quickly. I coincidentally came up with the same solution after comparing with the Vue StyleGuidist demo's.
