### ISSUE TITLE
npm audit error: regex DoS in marked

### ISSUE THREAD

**Issue by duckness** [ph1p/vuepress-jsdoc#42]
**Describe the bug**
A nested dependency of this repository is flagged by `npm audit`: `vuepress-jsdoc` > `jsdoc-to-markdown` > `dmd` > `marked`  
This can be fixed by updating the `jsdoc-to-markdown` version to the next major release.

**To Reproduce**
1. Run `npm audit`

**Expected behavior**
No vulns returned.

**Node (please complete the following information):**
 - Node-Version: 15.6.0

**Additional context**
N.A

**Comment by ph1p** [comment]
Hello @duckness thanks for reporting!
Fixed in the new version 3.5.0
