### ISSUE TITLE
mm.isMatch(path.join(folder.replace(srcFolder, ''), file) is not working properly

### ISSUE THREAD

**Issue by diegoazh** [ph1p/vuepress-jsdoc#43]
**Describe the bug**
On commit [554f804ec133a94db99a22eb5f1b110817a214452ce1868738fa5321237ce7a7](https://github.com/ph1p/vuepress-jsdoc/commit/5b8954757cafc4057a27439d25abfef3cc919680#diff-554f804ec133a94db99a22eb5f1b110817a214452ce1868738fa5321237ce7a7) the line 81 on `cmds/index.js` changes from
```js
mm.contains(`${chalk.dim(folder)}/${file}`, exclude)
```
to
```js
mm.isMatch(path.join(folder.replace(srcFolder, ''), file)
```
the problem is when the source folder is `./src` it replace it for an empty string (`''`) and `micromatch` use `picomatch` under the hood:

![image](https://user-images.githubusercontent.com/10166935/127758311-c0376ff3-357b-4be1-b492-7e6502d95e97.png)

and as you can see in line 47 of the next image if `glob` argument is equal to `''` it throws an error and brokes the process

![image](https://user-images.githubusercontent.com/10166935/127758537-97f2e46b-6c62-4d40-8537-be079eb60b41.png)

Ok, the question probably is why it is receiving the empty string on the `glob` of `picomatch`, is because in the change mentioned above, the `srcFolder` is replaced with `''` and in the first iteration the variable `folder` is the default value for the `--source` argument, I mean `./src`, you can check that in the following image

![image](https://user-images.githubusercontent.com/10166935/127758416-c02c225f-b06a-4eb5-b403-61a544652722.png)

**To Reproduce**

Is simple you need a repo with the following structure:

![image](https://user-images.githubusercontent.com/10166935/127758631-a19634f9-d093-4e44-b967-b2e165c41cd8.png)

and run the following command `npx vuepress-jsdoc`

**Expected behavior**
Works normally like as `v3.2.0` worked before the mentioned change.

**Node (please complete the following information):**
 - Node-Version: `v14.17.1`

**Additional context**

**Comment by ph1p** [comment]
Thank you! I'll take a look at it as soon as I can (:

**Comment by ph1p** [comment]
Hopefully it's fixed with the new version `3.6.0`. I removed every empty string inside the `exclude` array. Also I updated some dependencies. Thanks for reporting.

**Comment by diegoazh** [comment]
I will test the new version the next weekend, thank you!!!

**Comment by diegoazh** [comment]
This issue was resolved on the last released version but I have a new issue now 😅
