### ISSUE TITLE
.../node_modules/vuepress-jsdoc/node_modules/.bin/vue-docgen: not found

### ISSUE THREAD

**Issue by diegoazh** [ph1p/vuepress-jsdoc#44]
**Describe the bug**
I found the above error in the last version, for some reason `vue-docgen-api` is not installed inside of the `node_modules` of the `vuepress-jsdoc`, I'm not sure why but when it try to use it to generate the docs in line `145` of `cmds/index.js` it isn't there.
I add prints to the modules inside of the `node_modules` in `vuepress-jsdoc` and the `nodeModulesPath` and `rootProjectFolder` variables in the first and second screenshots in the last screenshot you can see the error `.../.bin/vue-docgen` module not found.

![Screenshot from 2021-08-22 17-24-25](https://user-images.githubusercontent.com/10166935/130369645-0681b1dc-6338-4d93-a039-72e5e2c1de42.png)
![Screenshot from 2021-08-22 17-26-09](https://user-images.githubusercontent.com/10166935/130369647-e8109592-3ba6-4f57-a623-81e5612d0d4f.png)
![Screenshot from 2021-08-22 17-40-39](https://user-images.githubusercontent.com/10166935/130369648-d5ed7d42-20ea-4f2f-b63a-c58b1de8c6bb.png)

**To Reproduce**
install `vuepress-jsdoc` and run the command to generate the documentation.

**Expected behavior**
Works in the same way as version `3.2.0` worked.

**Node (please complete the following information):**
 - Node-Version: `14.17.1`

**Additional context**
I had installed `vue-docgen-api` and `vue-docgen-cli` in my `devDependencies` but, I remove them from my `devDependencies` and I made a fresh install with a new `package-lock.json` generated and the error is still happening.

**Comment by diegoazh** [comment]
I think maybe you should find the executable on the `node_modules` of `vuepress-jsdoc` and if it doesn't found the executable found in `node_modules` of the main repository because in my case even removing it from my `devDependencies` when I make an install `vue-docgen-cli` is installed inside the root `node_modules` instead of the `vuepress-jsdoc` `node_modules` as you can see in the following image

![Screenshot from 2021-08-22 18-38-12](https://user-images.githubusercontent.com/10166935/130370788-4af798d0-1dd5-46b6-bd3c-f10ba7ac5f47.png)

**Comment by ph1p** [comment]
Thanks for reporting. It would be nice, if you can attach a zip or something else, with a minimal reproduceable example.

**Comment by diegoazh** [comment]
Hi @ph1p sorry for my delay I was very busy these days, here is the repository https://github.com/diegoazh/vuepress-jsdoc-issue, use the script `npm run gen:api:docs`

**Comment by ph1p** [comment]
@diegoazh thank you! It should be fixed now. I also reduced the dependencies in the same move.

**Comment by ph1p** [comment]
Thank you! Now it should work. I also dropped 3 dependencies. Version `3.7.1`.

**Comment by diegoazh** [comment]
Excellent, thank you @ph1p I will test it this weekend.

**Comment by ph1p** [comment]
@diegoazh In the meantime I have rewritten a lot :D It would be great if you could check if `4.0.4` works too.

**Comment by diegoazh** [comment]
@ph1p, yes I installed the last version and it works like a charm, thank you so much for the effort 🎊 🎉
