### ISSUE TITLE
Custom Readme

### ISSUE THREAD

**Issue by deka** [ph1p/vuepress-jsdoc#6]
Any news about this feature ? 
Without, i can't use your nice package
Regards

Or a workaround ?

**Comment by ph1p** [comment]
Hey! I'll take a look at it tomorrow. Maybe I need to implement a special filename assignment or a small flag to prevent overwriting files, so you can just add readme files by yourself.

**Comment by ph1p** [comment]
Done. (: https://github.com/ph1p/vuepress-jsdoc#custom-readme
