### ISSUE TITLE
add exclude feature

### ISSUE THREAD

**Issue by DophinL** [ph1p/vuepress-jsdoc#8]
great job!
but it seems not support exclude feature, everything under source folder would be included.
is there any plan for it?

**Comment by ph1p** [comment]
Good idea! I will add it as soon as possible (:

**Comment by ph1p** [comment]
@DophinL I've added a new flag to exclude files and folders. Feel free to test it in version 1.1.0 ;)

**Comment by DophinL** [comment]
great job, thanks!
