### ISSUE TITLE
if there is already a readme in code folder, don't override it

### ISSUE THREAD

**Issue by DophinL** [ph1p/vuepress-jsdoc#9]
in generate code folder, and want to maintain the readme there, instead of vuepress-jsdoc each time to copy readme there.
so can you add a feature to detect: if there is already a readme in code folder, don't override it

thanks!

**Comment by ph1p** [comment]
You can set --readme=./path/md_file.md or add a README.md to you source folder, but I can also add your feature request. 

> If there is a readme.md inside the destination folder, overwrite everything else except this file

**Comment by DophinL** [comment]
yes, I use this feature now, but I don't want to run vuepress-jsdoc each time when change the doc.

consider this scene: I just start to use vuepress, I need to change readme.md all the time to check whether meet my need, I just directly modify readme on docs folder.And when I need to run vuepress-jsdoc, it will override that readme.

Without this feature it still works, but some kind of inconvenient.

Please consider this thanks:D

**Comment by ph1p** [comment]
Oh yeah you're right... Didn't think about this case. I will implement it as fast as I can ;)

**Comment by ph1p** [comment]
Added @DophinL Now the README.md is no longer overwritten. Unless you're specifying it via the additional parameter `--rmPattern=./documentation/code/README.md`.
